-- 코드를 입력하세요

SELECT LEFT(SALES_DATE, 10), PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM (
SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
UNION
SELECT SALES_DATE, PRODUCT_ID,  NULL AS USER_ID, SALES_AMOUNT
FROM OFFLINE_SALE
WHERE YEAR(SALES_DATE)=2022 AND MONTH(SALES_DATE)=3
) A
ORDER BY SALES_DATE, PRODUCT_ID, COALESCE(USER_ID, 0);