-- 코드를 입력하세요
SELECT MONTH, CAR_ID, RECORDS
FROM (
    SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(CAR_ID) RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE LEFT(START_DATE, 7) BETWEEN '2022-08' AND '2022-10'
    GROUP BY MONTH, CAR_ID
) A WHERE (
    SELECT COUNT(CAR_ID) RECORDS
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE LEFT(START_DATE, 7) BETWEEN '2022-08' AND '2022-10' AND A.CAR_ID = CAR_ID
    GROUP BY CAR_ID
    HAVING RECORDS >= 5
) >= 5
ORDER BY MONTH, CAR_ID DESC;