-- 코드를 입력하세요
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, LEFT(B.CREATED_DATE, 10)
FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B USING (BOARD_ID)
WHERE A.CREATED_DATE LIKE '2022-10%'
ORDER BY B.CREATED_DATE, A.TITLE